### ISSUE TITLE
Generate model using original code (1-2)

### ISSUE THREAD

**Issue by nandrian-usc** [ENSOPredict/EnsoPredict#1]
**Related problem (if any) : **
Need to have model for comparison of better correlation

**Proposed Solution : **
Generate using professor given code while changing the parameter

**Additional Note : **
Look for better learning loss result, epoch around 40

**Task**
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 1)
- [x] Use both MPI dataset for training and testing (lead time 1) 
- [x] Compare correlation between using MPI+observations versus using MPI+MPI for training and testing
- [ ] Generate model with preferred option from above (lead time 2)
