### ISSUE TITLE
Setting up docker

### ISSUE THREAD

**Issue by nandrian-usc** [ENSOPredict/EnsoPredict#10]
**Related problem (if any) : **
EnsoPredict should be able to run in offline environment

**Proposed Solution : **
Implement EnsoPredict inside docker

**Additional Note : **
Load model pt. file into docker and output file into host computer drive

**Task**
- [x] Make dockerfile with environment requirements.txt
- [x] Test loading model pt. file into docker
- [x] Test outputing file into host computer drive
