### ISSUE TITLE
Make final report

### ISSUE THREAD

**Issue by nandrian-usc** [ENSOPredict/EnsoPredict#17]
**Related problem (if any) :**
Requirement for completion of project

**Proposed Solution :**
Make report in doc and put it into shared drive

**Additional Note :**
According lecture points checklist

**Task**
- [x] Make headers template
- [x] Make User manual
- [x] Make Appendix
- [x] Put into shared drive
- [ ] Submit to Client
