### ISSUE TITLE
Generate model using original code (5-8)

### ISSUE THREAD

**Issue by nandrian-usc** [ENSOPredict/EnsoPredict#2]
**Related problem (if any):**
Need to have model for comparison of better correlation

**Proposed Solution:**
Generate using professor given code while changing the parameter

**Additional Note:**
Look for better learning loss result, epoch around 40

**Task**
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 5)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 6)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 7)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 8)
