### ISSUE TITLE
Generate model using original code (9-12)

### ISSUE THREAD

**Issue by nandrian-usc** [ENSOPredict/EnsoPredict#3]
**Related problem (if any):**
Need to have model for comparison of better correlation

**Proposed Solution:**
Generate using professor given code while changing the parameter

**Additional Note:**
Look for better learning loss result, epoch around 40

**Task**
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 9)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 10)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 11)
- [x] Use MPI dataset for training and observations (sst) dataset for testing (lead time 12)
